apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-helloworld
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  selector:
    matchLabels:
      app: go-helloworld
  template:
    metadata:
      labels:
        app: go-helloworld
    spec:
      containers:
      - name: rollouts-demo
        image: nightmar39/go-helloworld:latest
        ports:
        - name: http
          containerPort: 6112
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
